### ISSUE TITLE
Not all secrets/resources getting created

### ISSUE THREAD

**Issue by MARVELMafia** [AzBuilder/terrakube-helm-chart#123]
I have directly installed terrakube via helm on my dev and it works perfectly.
When I try to install it via argoCD in prod via helm it seems it is not able to create some services and secrets. I am not sure why that is as I am using the same values.yaml which works in dev.

Below is the `values.yaml`

```
name: "terrakube"

## Terrakube Storage
storage:
  existingSecret: terrakube-minio-manual
  defaultStorage: true
  minio:
    bucketName: "iaac-infrastructure"
    endpoint: ""
  default:
    endpoint: ""

security:
  dexClientId: "keycloak"
  dexIssuerUri: https://<>/dex
  adminGroup: terrakubeAdmin
  existingSecret: terrakube-ca-secrets-manual


minio:
  existingSecret: terrakube-minio-manual
  defaultBuckets: "iaac-infrastructure"
  
## API properties
api:
  version: "2.19.2"
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  volumes:
    - name: ca-certs
      secret:
        secretName: terrakube-ca-secrets
        items:
        - key: "Fortinet.pem"
          path: "Fortinet.pem"
        - key: "type"
          path: "type"
  volumeMounts:
  - name: ca-certs
    mountPath: /mnt/platform/bindings/ca-certificates
    readOnly: true

registry:
  version: "2.19.2"
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  volumes:
    - name: ca-certs
      secret:
        secretName: terrakube-ca-secrets
        items:
        - key: "Fortinet.pem"
          path: "Fortinet.pem"
        - key: "type"
          path: "type"
  volumeMounts:
  - name: ca-certs
    mountPath: /mnt/platform/bindings/ca-certificates
    readOnly: true

executor:
  version: "2.19.2"
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  volumes:
    - name: ca-certs
      secret:
        secretName: terrakube-ca-secrets
        items:
        - key: "Fortinet.pem"
          path: "Fortinet.pem"
        - key: "type"
          path: "type"
  volumeMounts:
  - name: ca-certs
    mountPath: /mnt/platform/bindings/ca-certificates
    readOnly: true

dex:
  config:
    issuer: https://<>/dex
    storage:
      type: memory
    oauth2:
      responseTypes: ["code", "token", "id_token"]
    web:
      allowedOrigins: ['*']

    staticClients:
      - id: keycloak
        redirectURIs:
        - 'https://<>'
        - 'http://localhost:3000'
        - 'http://localhost:10001/login'
        - 'http://localhost:10000/login'
        - '/device/callback'
        name: 'keycloak'
        public: true

    connectors:
      - type: oidc
        id: keycloak
        name: keycloak
        config:          
          issuer: https://<> 
          clientID: terrakube
          clientSecret: <>
          redirectURI: https://<>/dex/callback
          scopes:
            - openid
            - profile
            - email
          insecureSkipEmailVerified: true
          insecureEnableGroups: true
          userIDKey: email
          userNameKey: email
          
ingress:
  useTls: true
  includeTlsHosts: true
  ui:
    enabled: true
    domain: "<>"
    path: "/"
    pathType: "Prefix"
    ingressClassName: "nginx"
    tlsSecretName: tls-secret-ui-terrakube
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
  api:
    enabled: true
    domain: "terrakube-api.<>"
    path: "/"
    pathType: "Prefix"
    ingressClassName: "nginx"
    tlsSecretName: tls-secret-api-terrakube
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
  registry:
    enabled: true
    domain: "terrakube-reg.<>"
    path: "/"
    pathType: "Prefix"
    ingressClassName: "nginx"
    tlsSecretName: tls-secret-reg-terrakube
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
  dex:
    enabled: true
    path: "/dex/"
    pathType: "Prefix"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
```

this is what gets created in prod with argocd helm in prod

![image](https://github.com/AzBuilder/terrakube-helm-chart/assets/28630442/98033303-f80b-4e0f-9c60-3fa7fbc46dc2)

and this is what gets created for the same values.yaml file in dev but without argocd but a direct apply via helm

![image](https://github.com/AzBuilder/terrakube-helm-chart/assets/28630442/268e13a2-75b8-498e-a1e3-c78cdaec00af)
