### ISSUE TITLE
Possible to support multiple domains for endpoints?

### ISSUE THREAD

**Issue by stanleyz** [AzBuilder/terrakube-helm-chart#127]
One domain per endpoints seems not enough in some situations, it's quite common that people set up prod instance with a CNAME to blue or green instance, but without multiple hosts configured in the ingress, cert-manager won't generate correct certificates with SANs, resulting in additional customised ingress being used instead of the ones provided in the chart.

**Comment by stanleyz** [comment]
what do you think of this @alfespa17, it will be something like:

```
ingress:
  ui:
    domains:
    - test1.com
    - test2.com
```

We can refer to the first domain in some secret configurations which require a URL to be generated from the old `domain` field. 

I have to admit that it's going to be a disruptive change.

**Comment by alfespa17** [comment]
Not sure if that will work because there are some configuration related to the ui url in the terrakube components (api and registry) so not sure if those will support to have several domains or if something will break internally.

**Comment by stanleyz** [comment]
I have been using multiple domains already but only registered in the TLS section and have annotation to tell nginx about the server aliases, something like below:

```
metadata:
  name: terrakube-registry-ingress
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/configuration-snippet: proxy_set_header Authorization
      $http_authorization;
    nginx.ingress.kubernetes.io/server-alias: terrakube-registry.example.net
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: internal-nginx
  
  tls:
  - hosts:
    - "terrakube-registry.minikube.net"
    - "terrakube-registry.example.net"
  ```
  
  I have the code ready, I'll put up a PR for you take a look whether it's acceptable.
