### ISSUE TITLE
Allow to configure service account and role bindings

### ISSUE THREAD

**Issue by dawidmalina** [AzBuilder/terrakube-helm-chart#132]
Follow up of the https://github.com/AzBuilder/terrakube/issues/635. It would be really good to have pre-configuration fully supported by helm chart.

Service account could be crated automatically with default value `terrakube-api-service-account` and configurable via `.Values.executor.serviceAccountName`.

Role and role bindings could be done automatically when setting `.Values.executor.rbac.create`.

This could unify setup by using only one tool (help).

**Comment by alfespa17** [comment]
You can use the following now @dawidmalina 

```
api:
  serviceAccountName: "terrakube-api-service-account"
  rbac:
    create: true
    roleName: "terrakube-api-role"
    roleBindingName: "terrakube-api-role-binding"
```
