### ISSUE TITLE
Issues with API pod starting

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terrakube-helm-chart#146]
Hi ! 

I've been trying to deploy a terrakube instance for my company behind a corporate proxy (AWS ALB). It seems like every pod are running fine except for executor, registry and API pod. When I take a look at both executor and registry pod logs I can see no error except that when I describe them I get the error (registry container)
```
  Warning  Unhealthy  15m   kubelet            Startup probe failed: Get "http://XX.XX.XX.XX:8075/actuator/health": dial tcp XX.XX.XX.XX:8075: connect: connection refused
```

From my understanding it is caused by the fact that no application is running on that port. The same error appears for executor container.

However, for the API container I have the following errors 

```
2024-10-04T13:06:14.561Z  INFO 1 --- [           main] com.amazonaws.http.AmazonHttpClient      : Configuring Proxy. Proxy Host: https://my-proxy/ Proxy Port: 443
2024-10-04T13:06:16.164Z  INFO 1 --- [           main] org.quartz.impl.StdSchedulerFactory      : Using default implementation for ThreadExecutor
2024-10-04T13:06:16.234Z  INFO 1 --- [           main] org.quartz.core.SchedulerSignalerImpl    : Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2024-10-04T13:06:16.235Z  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : Quartz Scheduler v2.5.0-rc1 created.
2024-10-04T13:06:16.249Z  INFO 1 --- [           main] o.s.s.quartz.LocalDataSourceJobStore     : Using db table-based data access locking (synchronization).
2024-10-04T13:06:16.252Z  INFO 1 --- [           main] o.s.s.quartz.LocalDataSourceJobStore     : JobStoreCMT initialized.
2024-10-04T13:06:16.253Z  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler meta-data: Quartz Scheduler (v2.5.0-rc1) 'schedulerFactoryBean' with instanceId 'terrakube-api-6f499d54f4-fmdz91728047176166'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.springframework.scheduling.quartz.LocalDataSourceJobStore' - which supports persistence. and is clustered.

2024-10-04T13:06:16.253Z  INFO 1 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler 'schedulerFactoryBean' initialized from an externally provided properties instance.
2024-10-04T13:06:16.253Z  INFO 1 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler version: 2.5.0-rc1
2024-10-04T13:06:16.253Z  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : JobFactory set to: org.terrakube.api.plugin.scheduler.configuration.QuartzAutoConfiguration$AutowireCapableBeanJobFactory@4ae19926
2024-10-04T13:06:16.340Z  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler schedulerFactoryBean_$_terrakube-api-6f499d54f4-fmdz91728047176166 started.
2024-10-04T13:06:16.733Z  INFO 1 --- [           main] a.p.s.j.t.e.e.K8sClientAutoConfiguration : Ephemeral Executor Configuration Image azbuilder/api-server:2.22.0, Namespace: terrakube, NodeSelector: null
2024-10-04T13:06:17.768Z  INFO 1 --- [           main] o.t.a.p.s.inactive.InactiveJobsService   : Setup job to cancelled inactive jobs
2024-10-04T13:06:17.772Z  INFO 1 --- [           main] o.t.a.p.s.inactive.InactiveJobsService   : Create Schedule for inactive jobs: DEFAULT.TerrakubeV2_InactiveJobs_394c1618-3f1c-4a87-9166-bbb3f19ca6b0
2024-10-04T13:06:17.942Z  INFO 1 --- [           main] o.t.a.p.s.inactive.InactiveJobsService   : jobDetail is null false
2024-10-04T13:06:17.943Z  INFO 1 --- [           main] o.t.a.p.s.inactive.InactiveJobsService   : Delete Old Quartz Job for inactive jobs
2024-10-04T13:06:18.151Z  INFO 1 --- [           main] o.t.a.p.s.inactive.InactiveJobsService   : Create Schedule Job Trigger for inactive jobs DEFAULT.TerrakubeV2_InactiveJobs
2024-10-04T13:06:18.342Z  INFO 1 --- [           main] o.t.a.p.scheduler.module.CacheService    : Run module index scan
2024-10-04T13:06:18.343Z  INFO 1 --- [           main] o.t.a.p.scheduler.module.CacheService    : Create Schedule Module Refresh: DEFAULT.TerrakubeV2_ModuleRefresh_6343d22a-069d-4d16-a3f9-5e6512ebc156
2024-10-04T13:06:18.434Z  INFO 1 --- [           main] o.t.a.p.scheduler.module.CacheService    : Disable Old Module Refresh
2024-10-04T13:06:18.453Z  INFO 1 --- [           main] o.t.a.p.scheduler.module.CacheService    : jobDetail is null false
2024-10-04T13:06:18.453Z  INFO 1 --- [           main] o.t.a.p.scheduler.module.CacheService    : Delete Old Quartz Job
2024-10-04T13:06:18.761Z  INFO 1 --- [           main] o.t.a.p.scheduler.module.CacheService    : Reschedule with new frequency
2024-10-04T13:06:18.764Z  INFO 1 --- [           main] o.t.a.p.scheduler.module.CacheService    : Create Schedule Job Trigger DEFAULT.TerrakubeV2_ModuleRefresh
2024-10-04T13:06:20.143Z ERROR 1 --- [ryBean_Worker-2] o.terrakube.api.rs.module.GitTagsCache   : https://github.com/Azure/terraform-azurerm-compute.git: cannot open git-upload-pack
2024-10-04T13:06:20.344Z ERROR 1 --- [ryBean_Worker-2] o.terrakube.api.rs.module.GitTagsCache   : https://github.com/Azure/terraform-azurerm-cosmosdb.git: cannot open git-upload-pack
2024-10-04T13:06:20.346Z ERROR 1 --- [ryBean_Worker-2] o.terrakube.api.rs.module.GitTagsCache   : https://github.com/Azure/terraform-azurerm-database.git: cannot open git-upload-pack
```
As it say `Exposing 1 endpoint beneath base path '/actuator'` I tried the connectivity to the endpoint and everything work fine but when I try another endpoint nothing works.

The main issue that I have is when using the UI of terrakube. I managed to get to the log in UI however, when I click on the login button nothing happens and the inspector tools shows the following error

```
Request URL:
https://my-proxy/dex/.well-known/openid-configuration
Request Method:
GET
Status Code:
401 Unauthorized
Remote Address:
34.250.194.57:443
Referrer Policy:
strict-origin-when-cross-origin
```

My understanding is that the API as it is not completely started does not provide the endpoint `dex/` and therefore when the UI tries to connect to it fails.

As mentioned in the documentation, i tried to add the 
```
  - name: JAVA_TOOL_OPTIONS
    value: "-Dhttps.proxyPort=8080 -Dhttps.proxyHost=https://my-proxy/"
```

But i still get the error
```
2024-10-04T13:06:20.143Z ERROR 1 --- [ryBean_Worker-2] o.terrakube.api.rs.module.GitTagsCache   : https://github.com/Azure/terraform-azurerm-compute.git: cannot open git-upload-pack
2024-10-04T13:06:20.344Z ERROR 1 --- [ryBean_Worker-2] o.terrakube.api.rs.module.GitTagsCache   : https://github.com/Azure/terraform-azurerm-cosmosdb.git: cannot open git-upload-pack
```
I don't know if this it was is preventing the API from properly starting but it's the only error I found when looking at the 3 pods.

Here's my values.yml if it is of any help
```
## API properties
api:
  #loadSampleData: true
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  - name: JAVA_OPTS
    value: "-Xmx512m -XX:MaxMetaspaceSize=1024m"
  - name: JAVA_TOOL_OPTIONS
    value: "-Dhttps.proxyPort=8080 -Dhttps.proxyHost=https://terrakube-api.my-proxy.net/"
  properties:
    databaseType: "H2"
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "1"

executor:
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  - name: JAVA_TOOL_OPTIONS
    value: "-Dhttps.proxyPort=8080 -Dhttps.proxyHost=https://terrakube-api.my-proxy.net/"
  podSecurityContext:
    runAsUser: 0
    runAsGroup: 1000
    fsGroup: 2000
  securityContext:
    runAsUser: 0

## Registry properties
registry:
  enabled: true
  replicaCount: "1"
  serviceType: "ClusterIP"
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  - name: JAVA_TOOL_OPTIONS
    value: "-Dhttps.proxyPort=8080 -Dhttps.proxyHost=https://terrakube-api.my-proxy.net/"

dex:
  config:
    issuer: https://terrakube-api.my-proxy.net/dex 

    storage:
      type: memory
    web:
      http: 0.0.0.0:5556
      allowedOrigins: ['*']
      skipApprovalScreen: true
    oauth2:
      responseTypes: ["code", "token", "id_token"]

    connectors:
    - type: ldap
      name: OpenLDAP
      id: ldap
      config:
        # The following configurations seem to work with OpenLDAP:
        #
        # 1) Plain LDAP, without TLS:
        host: terrakube-openldap-service:1389
        insecureNoSSL: true
        #
        # 2) LDAPS without certificate validation:
        #host: localhost:636
        #insecureNoSSL: false
        #insecureSkipVerify: true
        #
        # 3) LDAPS with certificate validation:
        #host: YOUR-HOSTNAME:636
        #insecureNoSSL: false
        #insecureSkipVerify: false
        #rootCAData: 'CERT'
        # ...where CERT="$( base64 -w 0 your-cert.crt )"

        # This would normally be a read-only user.
        bindDN: cn=admin,dc=example,dc=org
        bindPW: admin

        usernamePrompt: Email Address

        userSearch:
          baseDN: ou=users,dc=example,dc=org
          filter: "(objectClass=person)"
          username: mail
          # "DN" (case sensitive) is a special attribute name. It indicates that
          # this value should be taken from the entity's DN not an attribute on
          # the entity.
          idAttr: DN
          emailAttr: mail
          nameAttr: cn

        groupSearch:
          baseDN: ou=Groups,dc=example,dc=org
          filter: "(objectClass=groupOfNames)"

          userMatchers:
            # A user is a member of a group when their DN matches
            # the value of a "member" attribute on the group entity.
          - userAttr: DN
            groupAttr: member

          # The group name should be the "cn" value.
          nameAttr: cn

    staticClients:
    - id: keycloak-app
      redirectURIs:
      - 'terrakube.my-proxy.net'
      - '/device/callback'
      name: 'keycloak-app'
      public: true

## Ingress properties
ingress:
  useTls: true
  includeTlsHosts: true
  ui:
    enabled: false
    domain: "terrakube.my-proxy.net"
    path: "/"
    pathType: "Prefix"
    ingressClassName: "alb"
    tlsSecretName: tls-secret-ui-terrakube

  api:
    enabled: false
    domain: "terrakube-api.my-proxy.net"
    path: "/"
    pathType: "Prefix"
    ingressClassName: "alb"
    tlsSecretName: tls-secret-api-terrakube

  registry:
    enabled: false
    domain: "terrakube-reg.my-proxy.net"
    path: "/"
    pathType: "Prefix"
    ingressClassName: "alb"
    tlsSecretName: tls-secret-reg-terrakube

  dex:
    enabled: false
    path: "/dex/"
    pathType: "Prefix"
    ingressClassName: "alb"
```

Thanks for your help !

**Comment by BenjaminDecreusefond** [comment]
Thanks for your quick answer ! 

I tried to give more power to my API pod but I still get the same error unfortunately. I manage to get all the pods in `Running` state like you but it's still impossible to go further than than the login page :( 
I will try to update my values.yml with the proper keycloak set up and let you know if it gets any better ! 

Have a good week end!

**Comment by BenjaminDecreusefond** [comment]
Hi !

I'm sorry to come back to you but I have a question regarding terrakube that I don't really understand ! 

I managed to make all pods launch and get to the login UI. However, when I click on the login button nothing happens sadly :( 

When i take a look at the network tab I'm seeing a 401 on the API endpoint under `https://terrakube-api.net/dex/.well-known/openid-configuration`. I have no issue to get a 200 on other endpoints like `actuator/health`.

From my point of view it looks like the endpoint api/dex does not exist ? But I think the issue lies somewhere else. I had the same issue with minikube and I'm getting a little lost :( 

I'm taking if you have any thoughts, 

Regards ! 
Benjamin

**Comment by alfespa17** [comment]
> Hi !
> 
> I'm sorry to come back to you but I have a question regarding terrakube that I don't really understand !
> 
> I managed to make all pods launch and get to the login UI. However, when I click on the login button nothing happens sadly :(
> 
> When i take a look at the network tab I'm seeing a 401 on the API endpoint under `https://terrakube-api.net/dex/.well-known/openid-configuration`. I have no issue to get a 200 on other endpoints like `actuator/health`.
> 
> From my point of view it looks like the endpoint api/dex does not exist ? But I think the issue lies somewhere else. I had the same issue with minikube and I'm getting a little lost :(
> 
> I'm taking if you have any thoughts,
> 
> Regards ! Benjamin

Just to clarify, dex and the api are 2 different components.

When we deploy it to terrakube we simply publish two services using the same domain just to simplify a little bit the deployment for testing purposes.

The API is deploy to `terrakube-api.minikube.net`  and we publish DEX to `terrakube-api.minikube.net/dex`, you can see this in this lines.

https://github.com/AzBuilder/terrakube-helm-chart/blob/efd3585024cd7236cabfd389ed090d3d2add721f/charts/terrakube/templates/ingress-api.yaml#L34

https://github.com/AzBuilder/terrakube-helm-chart/blob/efd3585024cd7236cabfd389ed090d3d2add721f/charts/terrakube/templates/ingress-api.yaml#L46

The above shows one endpoint but exposing 2 different kubernetes services.

I hope this can help you.

**Comment by BenjaminDecreusefond** [comment]
I better understand thank you ! If I follow you well I should expose my dex service as well to be able to access it though my UI ?

**Comment by alfespa17** [comment]
> I better understand thank you ! If I follow you well I should expose my dex service as well to be able to access it though my UI ?

@BenjaminDecreusefond you can have `terrakube-api.minikube.net` and `terrakube-dex.minikube.net` and it will work as long as you put the correct dex configuration for terrakube to know where the DEX endpoint is exposed

```yaml
dex:
  enabled: false
  config:
    issuer: terrakube-dex.minikube.net
```

The above will be like having an external DEX service instead of using the default one.

**Comment by BenjaminDecreusefond** [comment]
I do agree with you ! It's what I've done (I think ?)
```
dex:
  enabled: true
  config:
    issuer: https://terrakube-api.minikube.net/dex

    storage:
      type: memory
    web:
      http: 0.0.0.0:5556
      allowedOrigins: ['*']
      skipApprovalScreen: true
    oauth2:
      responseTypes: ["code", "token", "id_token"]

      connectors:
      - type: ldap
        name: OpenLDAP
        id: ldap
        config:
          host: terrakube-openldap-service:389
          insecureNoSSL: true

          bindDN: cn=admin,dc=example,dc=org
          bindPW: admin
          usernamePrompt: Email Address
          userSearch:
            baseDN: ou=People,dc=example,dc=org
            filter: "(objectClass=person)"
            username: mail

            idAttr: DN
            emailAttr: mail
            nameAttr: cn
          groupSearch:
            baseDN: ou=Groups,dc=example,dc=org
            filter: "(objectClass=groupOfNames)"
            userMatchers:
              # A user is a member of a group when their DN matches
              # the value of a "member" attribute on the group entity.
            - userAttr: DN
              groupAttr: member
            # The group name should be the "cn" value.
            nameAttr: cn
      staticClients:
      - id: example-app
        redirectURIs:
        - 'https://terrakube.minikube.net'
        - '/device/callback'
        - 'http://localhost:10000/login'
        - 'http://localhost:10001/login'
        name: 'example-app'
        public: true
```
I kept the default config for dex but when I click on the login button it throws 401 on 
`https://terrakube-api.minikube.net/dex/.well-known/openid-configuration`

**Comment by alfespa17** [comment]
> I do agree with you ! It's what I've done (I think ?)
> 
> ```
> dex:
>   enabled: true
>   config:
>     issuer: https://terrakube-api.minikube.net/dex
> 
>     storage:
>       type: memory
>     web:
>       http: 0.0.0.0:5556
>       allowedOrigins: ['*']
>       skipApprovalScreen: true
>     oauth2:
>       responseTypes: ["code", "token", "id_token"]
> 
>       connectors:
>       - type: ldap
>         name: OpenLDAP
>         id: ldap
>         config:
>           host: terrakube-openldap-service:389
>           insecureNoSSL: true
> 
>           bindDN: cn=admin,dc=example,dc=org
>           bindPW: admin
>           usernamePrompt: Email Address
>           userSearch:
>             baseDN: ou=People,dc=example,dc=org
>             filter: "(objectClass=person)"
>             username: mail
> 
>             idAttr: DN
>             emailAttr: mail
>             nameAttr: cn
>           groupSearch:
>             baseDN: ou=Groups,dc=example,dc=org
>             filter: "(objectClass=groupOfNames)"
>             userMatchers:
>               # A user is a member of a group when their DN matches
>               # the value of a "member" attribute on the group entity.
>             - userAttr: DN
>               groupAttr: member
>             # The group name should be the "cn" value.
>             nameAttr: cn
>       staticClients:
>       - id: example-app
>         redirectURIs:
>         - 'https://terrakube.minikube.net'
>         - '/device/callback'
>         - 'http://localhost:10000/login'
>         - 'http://localhost:10001/login'
>         name: 'example-app'
>         public: true
> ```
> 
> I kept the default config for dex but when I click on the login button it throws 401 on `https://terrakube-api.minikube.net/dex/.well-known/openid-configuration`

Can you share the complete yaml? (without sensitive data)

**Comment by alfespa17** [comment]
@BenjaminDecreusefond lets go step by step.

For the API configuration I saw you have SERVICE_BINDING_ROOT, I guess you want to add some internal certificate so it should look like this:

```yaml
security:
  caCerts:
    terrakubeDemo1.pem: |
      -----BEGIN CERTIFICATE-----

      CERTIFICATE DATA

      -----END CERTIFICATE-----
    terrakubeDemo2.pem: |
      -----BEGIN CERTIFICATE-----

      CERTIFICATE DATA

      -----END CERTIFICATE-----

## API properties
api:
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  - name: JAVA_OPTS
    value: "-Xmx512m -XX:MaxMetaspaceSize=1024m"
  properties:
    databaseType: "H2"
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
  volumes:
    - name: ca-certs
      secret:
        secretName: terrakube-ca-secrets
        items:
        - key: "terrakubeDemo1.pem"
          path: "terrakubeDemo1.pem"
        - key: "terrakubeDemo2.pem"
          path: "terrakubeDemo2.pem"
        - key: "type"
          path: "type"
  volumeMounts:
  - name: ca-certs
    mountPath: /mnt/platform/bindings/ca-certificates
    readOnly: true
```

The same should happen with the Registry and Executor configuration if you want to add a custom CA certificate.

```yaml
executor:
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  podSecurityContext:
    runAsUser: 0
    runAsGroup: 1000
    fsGroup: 2000
  securityContext:
    runAsUser: 0
  volumes:
    - name: ca-certs
      secret:
        secretName: terrakube-ca-secrets
        items:
        - key: "terrakubeDemo1.pem"
          path: "terrakubeDemo1.pem"
        - key: "terrakubeDemo2.pem"
          path: "terrakubeDemo2.pem"
        - key: "type"
          path: "type"
  volumeMounts:
  - name: ca-certs
    mountPath: /mnt/platform/bindings/ca-certificates
    readOnly: true

## Registry properties
registry:
  enabled: true
  replicaCount: "1"
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  volumes:
    - name: ca-certs
      secret:
        secretName: terrakube-ca-secrets
        items:
        - key: "terrakubeDemo1.pem"
          path: "terrakubeDemo1.pem"
        - key: "terrakubeDemo2.pem"
          path: "terrakubeDemo2.pem"
        - key: "type"
          path: "type"
  volumeMounts:
  - name: ca-certs
    mountPath: /mnt/platform/bindings/ca-certificates
    readOnly: true
```

I dont work with AWS but I saw in another issue that you need to use `ImplementationSpecific` in some comments [here](https://github.com/AzBuilder/terrakube-helm-chart/issues/93#issuecomment-2397810758)

```yaml
## Ingress properties
ingress:
  useTls: true
  includeTlsHosts: true

  ui:
    enabled: true
    domain: "terrakube.YOUR-CUSTOM-DOMAIN.net"
    path: "/*"
    pathType: "ImplementationSpecific"
    ingressClassName: "alb"
    tlsSecretName: tls-secret-ui-terrakube

  api:
    enabled: true
    domain: "terrakube-api.YOUR-CUSTOM-DOMAIN.net"
    path: "/*"
    pathType: "ImplementationSpecific"
    ingressClassName: "alb"
    tlsSecretName: tls-secret-api-terrakube

  registry:
    enabled: true
    domain: "terrakube-reg.YOUR-CUSTOM-DOMAIN.net"
    path: "/*"
    pathType: "ImplementationSpecific"
    ingressClassName: "alb"
    tlsSecretName: tls-secret-reg-terrakube

  dex:
    enabled: true
    path: "/dex/"
    pathType: "ImplementationSpecific"
    ingressClassName: "alb"

```

Not sure if you are using the openldap sample data but from what I can see you need to update the values to use your custom domain.

You could check [dex documentation](https://dexidp.io/docs/connectors/) to learn more about the connectors.

```yaml
security:
  dexClientId: example-app # From the static client configuration below
  useOpenLDAP: true

dex:
  enabled: true
  config:
    issuer: https://terrakube-api.YOUR-CUSTOM-DOMAIN.net/dex

    storage:
      type: memory
    web:
      http: 0.0.0.0:5556
      allowedOrigins: ['*']
      skipApprovalScreen: true
    oauth2:
      responseTypes: ["code", "token", "id_token"]

      connectors:
      - type: ldap
        name: OpenLDAP
        id: ldap
        config:
          host: terrakube-openldap-service:389
          insecureNoSSL: true

          bindDN: cn=admin,dc=example,dc=org
          bindPW: admin
          usernamePrompt: Email Address
          userSearch:
            baseDN: ou=People,dc=example,dc=org
            filter: "(objectClass=person)"
            username: mail

            idAttr: DN
            emailAttr: mail
            nameAttr: cn
          groupSearch:
            baseDN: ou=Groups,dc=example,dc=org
            filter: "(objectClass=groupOfNames)"
            userMatchers:
              # A user is a member of a group when their DN matches
              # the value of a "member" attribute on the group entity.
            - userAttr: DN
              groupAttr: member
            # The group name should be the "cn" value.
            nameAttr: cn
      staticClients:
      - id: example-app
        redirectURIs:
        - 'https://terrakube.YOUR-CUSTOM-DOMAIN.net'
        - '/device/callback'
        - 'http://localhost:10000/login'
        - 'http://localhost:10001/login'
        name: 'example-app'
        public: true
```

For your issue with the dex endopint you can check this file to see how the helm chart is generating the ingress configuration and validate if maybe you need to do some updates.

https://github.com/AzBuilder/terrakube-helm-chart/blob/main/charts/terrakube/templates/ingress-api.yaml

I hope this can help.
