### ISSUE TITLE
Missing memory requirements for Helm deployment

### ISSUE THREAD

**Issue by dirsigler** [AzBuilder/terrakube-helm-chart#163]
I am trying to install Terrakube as a Proof of Concept, but unfortunately run into issues with the memory requirements of the application.

For my small Civo cluster I receive from the `terrakube-executor` following error message when trying to start the Pod:
```
Calculating JVM memory based on 464280K available memory
For more information on this calculation, see https://paketo.io/docs/reference/java-reference/#memory-calculator
unable to calculate memory configuration
fixed memory regions require 719365K which is greater than 464280K available for allocation: -XX:MaxDirectMemorySize=10M, -XX:MaxMetaspaceSize=207365K, -XX:ReservedCodeCacheSize=240M, -Xss1M * 250 threads
ERROR: failed to launch: exec.d: failed to execute exec.d file at path '/layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/memory-calculator': exit status 1
stream closed EOF for terrakube/terrakube-executor-5dfcb8f6f9-qgc7d (terrakube-executor)
```

In the values.yaml I could not find any configuration to reduce the memory consumption.
For the documentation I also could not find any information about the required hardware resources available.

Is there any chance we can reduce the required memory or add the required resources to the [Architecture](https://docs.terrakube.io/getting-started/design-and-architecture) page?

**Comment by alfespa17** [comment]
Hello @dirsigler 

You can customize JVM configuration using the following environment variable `JAVA_TOOL_OPTIONS` like we did with the proxy settings [here](https://docs.terrakube.io/getting-started/deployment/proxy-configuration)

Example:
```
api:
  env:
  - name: JAVA_TOOL_OPTIONS
    value: "-Dhttp.proxyHost=your.proxy.net -Dhttp.proxyPort=8080 -Dhttp.nonProxyHosts=XXXXX -Dhttps.proxyHost=your.proxy.net -Dhttps.proxyPort=8080 -Dhttps.nonProxyHosts=XXXXX"
    
registry:
  env:
  - name: JAVA_TOOL_OPTIONS
    value: "-Dhttp.proxyHost=your.proxy.net -Dhttp.proxyPort=8080 -Dhttp.nonProxyHosts=XXXXX -Dhttps.proxyHost=your.proxy.net -Dhttps.proxyPort=8080 -Dhttps.nonProxyHosts=XXXXX"

executor:
  env:
  - name: JAVA_TOOL_OPTIONS
    value: "-Dhttp.proxyHost=your.proxy.net -Dhttp.proxyPort=8080 -Dhttp.nonProxyHosts=XXXXX -Dhttps.proxyHost=your.proxy.net -Dhttps.proxyPort=8080 -Dhttps.nonProxyHosts=XXXXX"
```

I run terrakube in minikube and it work correctly with 2 cpus and 6 gb of ram
