### ISSUE TITLE
Incompatible with Google Certificates on GKE

### ISSUE THREAD

**Issue by jtrouth** [AzBuilder/terrakube-helm-chart#61]
The use of the `ingress.useTls` value to control both the Ingress TLS spec and the scheme of URLs in the app config make this chart not work with Google Certificates on the GCE-native Ingress. This is because [annotations are used to attach Google managed](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs#setting_up_a_google-managed_certificate) or self-managed certificates to an Ingress resource.

If you set `ingress.useTls` to `true` the Ingresses will fail to create GCE Load Balancers because the TLS secret does not exist, and if you set it to `false` the Oauth redirect URI will use HTTP instead of HTTPS. Allowing independent control of the Ingress TLS spec and the relevant portions of the app config should resolve.

**Comment by alfespa17** [comment]
Hello @jtrouth I dont have experience with the Google Kubernetes Engine and Google Managed Certificates but I was checking the documentation that you provided I think that in that case you could create the managed certificate before deploying the helm chart, I think it will be something like this:

```yaml
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
spec:
  domains:
    - terrakube-ui.minikube.net
    - terrakube-api.minikube.net
    - terrakube-reg.minikube.net
```

Once you have created the managed certificate you could customize the ingress annotation using a custom file value.yaml to something like this:

```yaml
## Ingress properties
ingress:
  useTls: true
  ui:
    enabled: true
    domain: "terrakube-ui.minikube.net"
    path: "/(.*)"
    pathType: "Prefix" 
    annotations:
      kubernetes.io/ingress.global-static-ip-name: ADDRESS_NAME
      networking.gke.io/managed-certificates: managed-cert
      kubernetes.io/ingress.class: "gce"
  api:
    enabled: true
    domain: "terrakube-api.minikube.net"
    path: "/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.global-static-ip-name: ADDRESS_NAME
      networking.gke.io/managed-certificates: managed-cert
      kubernetes.io/ingress.class: "gce"
  registry:
    enabled: true
    domain: "terrakube-reg.minikube.net"
    path: "/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.global-static-ip-name: ADDRESS_NAME
      networking.gke.io/managed-certificates: managed-cert
      kubernetes.io/ingress.class: "gce"
  dex:
    enabled: true
    path: "/dex/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.global-static-ip-name: ADDRESS_NAME
      networking.gke.io/managed-certificates: managed-cert
      kubernetes.io/ingress.class: "gce"
```

And deploy the app using the helm install:

```bash
helm install --values values.yaml terrakube terrakube-repo/terrakube -n terrakube
```

In the example documentation I also saw that it was using NodePort, by the default the helm chart is using ClusterIp, you could change that if need it using something like this in your values.yaml:

```yaml
## API properties
api:
  serviceType: "NodePort"

## Executor properties
executor:
  serviceType: "NodePort"

## Registry properties
registry:
  serviceType: "NodePort"

## Registry properties
registry:
  serviceType: "NodePort"
```

I hope this can help you.
