### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by AlarleCKe** [AzBuilder/terrakube-helm-chart#68]
Hello,

today i deployed Terrakube on an AKS Cluster by pretty much following the example [AzureAuthentication-Example1](https://github.com/AzBuilder/terrakube-helm-chart/blob/main/examples/AzureAuthentication-Example1.md). 

I´ve created an Azure AD Group called `terrakube-admin-access`,  created an Azure AD Application, and a Storage-Account.  
In my `values.yaml` I´ve added the Storage Account Name, aswell ass the Ressource Group and the Access Key of it 
Within the `connectors` section of dex I´ve added the Client ID, the Tenant ID and the Client-Secret of my Azure AD Application,

However, after deploying the Chart, clicking on the `Login` button from the UI does nothing. 
Unfortunately i do not see any log message in any of the components. 
I was hoping that someone could point out what is missing in my setup.

Here is my `values.yaml`

```
## Terrakube Security
security:
  useOpenLDAP: false
  adminGroup: "terrakube-admin-access"
  patSecret: "<<REDACTED>>"
  internalSecret: "<<REDACTED>>"
  dexClientId: "microsoft"
  dexClientScope: "email openid profile offline_access groups"
  dexIssuerUri: "https://terrakube-api.my-domain.internal/dex"

## Terraform Storage
storage:
  defaultStorage: false
  azure:
    storageAccountName: "<<REDACTED>>"
    storageAccountResourceGroup: "<<REDACTED>>"
    storageAccountAccessKey: "<<REDACTED>>"

## Dex
dex:
  enabled: true
  version: "v2.32.0"
  replicaCount: "1"
  serviceType: "ClusterIP"
  useOpenLDAP: false
  config:
    issuer: https://terrakube-api.my-domain.internal/dex
    storage:
      type: memory
    oauth2:
      responseTypes: ["code", "token", "id_token"] 
      skipApprovalScreen: true
    web:
      allowedOrigins: ['*']
      logger:
    staticClients:
    - id: microsoft
      redirectURIs:
      - 'https://terrakube.my-domain.internal'
      - 'http://localhost:3000'
      - 'http://localhost:10001/login'
      - 'http://localhost:10000/login'
      - '/device/callback'
      name: 'microsoft'
      public: true
    connectors:
    - type: microsoft
      id: microsoft
      name: microsoft
      config:
        clientID: "<<REDACTED>>"
        clientSecret: "<<REDACTED>>"
        redirectURI: "https://terrakube-api.my-domain.internal/dex/callback"
        tenant: "<<REDACTED>>"

## API properties
api:
  enabled: true
  defaultDatabase: false
  version: "2.10.0"
  replicaCount: "1"
  serviceType: "ClusterIP"
  properties:
    databaseType: "H2"

## Executor properties
executor:
  enabled: true
  version: "2.10.0"  
  replicaCount: "1"
  serviceType: "ClusterIP"
  properties:
    toolsRepository: "https://github.com/AzBuilder/terrakube-extensions"
    toolsBranch: "main"

## Registry properties
registry:
  enabled: true
  version: "2.10.0"
  replicaCount: "1"
  serviceType: "ClusterIP"

## UI Properties
ui:
  enabled: true
  version: "2.10.0"
  replicaCount: "1"
  serviceType: "ClusterIP"

## Ingress properties
ingress:
  useTls: true
  ui:
    enabled: true
    domain: "terrakube.my-domain.internal"
    path: "/(.*)"
    pathType: "Prefix" 
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: "my-domain-internal"
      external-dns/zone: "my-domain.internal"
  api:
    enabled: true
    domain: "terrakube-api.my-domain.internal"
    path: "/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: "my-domain-internal"
      external-dns/zone: "my-domain.internal"
  registry:
    enabled: true
    domain: "terrakube-reg.my-domain.internal"
    path: "/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: "my-domain-internal"
      external-dns/zone: "my-domain.internal"
  dex:
    enabled: true
    path: "/dex/(.*)"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header Authorization $http_authorization;"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: "my-domain-internal"
      external-dns/zone: "my-domain.internal"
```
